File "/usr/local/lib/python3.4/dist-packages/appdaemon/appdaemon.py", line 418, in worker
    function(ha.sanitize_timer_kwargs(args["kwargs"]))
TypeError: 'NoneType' object is not callable
